// ==UserScript==
// @ScriptName        金十数据净化[墨鱼版]
// @Author            @ddgksf2013
// @Function          如果有需要的去除广告的APP，可自行在共享表格中添加需求
// @AddRequest        https://bit.ly/addRequestforAdBlock
// @WechatID          墨鱼手记
// @TgChannel         https://t.me/ddgksf2021
// @Contribute        https://t.me/ddgksf2013_bot
// @Feedback          📮 ddgksf2013@163.com 📮
// @UpdateTime        2026-01-10
// @Suitable          自行观看“# > ”注释内容
// @Attention         如需引用请注明出处，谢谢合作！
// @Version           V1.0.2
// @ScriptURL         https://ddgksf2013.top/rewrite/JinShiDataAds.conf
// ==/UserScript==

hostname = search-open-api.jin10.com, jad-api.jin10.com, 121.40.226.146, 121.40.189.47, 120.55.71.177, 121.40.128.214, 121.40.195.238, 

^https?:\/\/jad-api\.jin10\.com\/ad url reject-200
^https?:\/\/search-open-api\.jin10\.com\/search\/getHotWords url jsonjq-response-body '.data.list=[]'
^https?:\/\/jad-api\.jin10\.com\/mult\/list_unread\?display=flash_list&fit_type=new_flash_flash url reject-200
