// ==UserScript==
// @ScriptName        瑞幸咖啡净化[墨鱼版]
// @Author            @ddgksf2013
// @Function          如果有需要的去除广告的APP，可自行在共享表格中添加需求
// @AddRequest        https://bit.ly/addRequestforAdBlock
// @WechatID          墨鱼手记
// @TgChannel         https://t.me/ddgksf2021
// @Contribute        https://t.me/ddgksf2013_bot
// @Feedback          📮 ddgksf2013@163.com 📮
// @UpdateTime        2026-08-20
// @Suitable          自行观看“# > ”注释内容
// @Attention         如需引用请注明出处，谢谢合作！
// @Version           V1.0.1
// @ScriptURL         https://ddgksf2013.top/rewrite/LuckinCoffeeAds.conf
// ==/UserScript==


hostname = capi.lkcoffee.com, 119.29.29.87

^https:\/\/capi\.lkcoffee\.com\/resource\/(?:m\/(?:sys\/(?:config\/value|common\/modules|homePage\/(?:common|contactor)\/modules|base\/myPageSectionShow\/newUI|app\/(?:adposNew|carousel)|visual\/effect\/modules)|aigc\/showAIButton)|seckill\/ar\/campaignBaseInfo) url script-response-body https://ddgksf2013.top/scripts/luckincoffee.ads.js
^https:\/\/119\.29\.29\.87\/d url reject-200
