// ==UserScript==
// @ScriptName        航旅纵横净化[墨鱼版]
// @Author            @ddgksf2013
// @Function          如果有需要的去除广告的APP，可自行在共享表格中添加需求
// @AddRequest        https://bit.ly/addRequestforAdBlock
// @WechatID          墨鱼手记
// @TgChannel         https://t.me/ddgksf2021
// @Contribute        https://t.me/ddgksf2013_bot
// @Feedback          📮 ddgksf2013@163.com 📮
// @UpdateTime        2026-08-29
// @Suitable          自行观看“# > ”注释内容
// @Attention         如需引用请注明出处，谢谢合作！
// @Version           V1.0.1
// @ScriptURL         https://ddgksf2013.top/rewrite/UmetripAds.conf
// ==/UserScript==


hostname = sns.umetrip.com, appmsg.umetrip.com, umehome.umetrip.com, opactivity.umetrip.com, activity.umetrip.com, umerp.umetrip.com, umeflightstatus.umetrip.com, umestartup.umetrip.com, oss.umetrip.com

^https:\/\/(?:sns|appmsg|umehome|opactivity|activity|umerp|umeflightstatus|umestartup)\.umetrip\.com\/gateway\/api\/umetrip\/native$ url script-response-body https://ddgksf2013.top/scripts/umetrip.ads.js
