// ==UserScript==
// @ScriptName        中羽在线净化[墨鱼版]
// @Author            @ddgksf2013
// @Function          如果有需要的去除广告的APP，可自行在共享表格中添加需求
// @AddRequest        https://bit.ly/addRequestforAdBlock
// @WechatID          墨鱼手记
// @TgChannel         https://t.me/ddgksf2021
// @Contribute        https://t.me/ddgksf2013_bot
// @Feedback          📮 ddgksf2013@163.com 📮
// @UpdateTime        2026-08-18
// @Suitable          自行观看“# > ”注释内容
// @Attention         如需引用请注明出处，谢谢合作！
// @Version           V1.0.5
// @ScriptURL         https://ddgksf2013.top/rewrite/ZhongYuZaiXianAds.conf
// ==/UserScript==


hostname = app.badmintoncn.com, www.badmintoncn.com, pc-mon.snssdk.com


# > 开屏 / 首页浮窗 / 轮播 Banner / 弹窗
^https:\/\/app\.badmintoncn\.com\/mag\/operative\/v1\/ad\/listNotEndByPlace url jsonjq-response-body '.list=[]'
# > 首页轮播组件
^https:\/\/app\.badmintoncn\.com\/mag\/info\/v\d+\/channel\/channelConfigById url jsonjq-response-body '.data.operative_config=((.data.operative_config // []) | map(select(._type!="pic_slide")))'
# > 信息流广告
^https:\/\/app\.badmintoncn\.com\/mag\/info\/v\d+\/(?:channel|info)\/infoListByCatId url jsonjq-response-body '.list=((.list // []) | map(select(._type!="pic_ad")))'
# > 我页中羽小店 / 推广 / 红包 / 优惠券
^https:\/\/app\.badmintoncn\.com\/mag\/user\/v\d+\/user\/myCenter url jsonjq-response-body '.list=((.list // []) | map(select(.name!="中羽小店")) | map(if .title=="我的权益" then .items=((.items // []) | map(select(.title!="我的推广" and .title!="每日红包" and .title!="优惠券"))) else . end))'
# > 社区商业街
^https:\/\/app\.badmintoncn\.com\/mag\/circle\/v\d+\/Circle\/circleRecommend url jsonjq-response-body '.tops=((.tops // []) | map(select(.name!="中羽商业街")))'
# > 中羽助手推广消息
^https:\/\/app\.badmintoncn\.com\/mag\/operative\/v\d+\/assistant\/pullAssistantMsg url jsonjq-response-body '.list=((.list // []) | map(select((((.content | tostring) | contains("cbo_gg/count.php")) == false))))'
# > 发现页网页广告 iframe
^https:\/\/app\.badmintoncn\.com\/mag\/config\/v\d+\/iframe\/iframeView\?id=13 url reject-200
# > 网页广告内容
^https:\/\/www\.badmintoncn\.com\/cboa\.php url reject-200
# > SDK 监控上报
^https:\/\/pc-mon\.snssdk\.com\/monitor_pc\/collect\/api\/pc_log url reject-200
