// ==UserScript==
// @ScriptName        小红书屏蔽首页及本地视频[墨鱼版]
// @Author            @ddgksf2013
// @Function          如果有需要的去除广告的APP，可自行在共享表格中添加需求
// @AddRequest        https://bit.ly/addRequestforAdBlock
// @WechatID          墨鱼手记
// @TgChannel         https://t.me/ddgksf2021
// @Contribute        https://t.me/ddgksf2013_bot
// @Feedback          📮 ddgksf2013@163.com 📮
// @UpdateTime        2026-04-18
// @Suitable          自行观看“# > ”注释内容
// @Attention         如需引用请注明出处，谢谢合作！
// @Version           V1.0.1
// @ScriptURL         https://ddgksf2013.top/rewrite/XiaoHongShuBlockVideo.conf
// ==/UserScript==


hostname = *.xiaohongshu.com

^https?:\/\/[a-z]+\.xiaohongshu\.com\/api/sns/v\d/(homefeed|localfeed) url jsonjq-response-body '.data |= map(select(.type == "normal"))'
