// ==UserScript==
// @ScriptName        智联招聘净化[墨鱼版]
// @Author            @ddgksf2013
// @Function          如果有需要的去除广告的APP，可自行在共享表格中添加需求
// @AddRequest        https://bit.ly/addRequestforAdBlock
// @WechatID          墨鱼手记
// @TgChannel         https://t.me/ddgksf2021
// @Contribute        https://t.me/ddgksf2013_bot
// @Feedback          📮 ddgksf2013@163.com 📮
// @UpdateTime        2026-03-09
// @Suitable          自行观看“# > ”注释内容
// @Attention         如需引用请注明出处，谢谢合作！
// @Version           V1.0.1
// @ScriptURL         https://ddgksf2013.top/rewrite/ZhiLianZhaoPinAds.conf
// ==/UserScript==





hostname = cgate.zhaopin.com


^https?:\/\/cgate\.zhaopin\.com\/behavior\/nps\/getNpsPopupList url reject
^https?:\/\/cgate\.zhaopin\.com\/operation\/ad\/ url reject
^https?:\/\/cgate\.zhaopin\.com\/marketbusiness\/ad\/ url reject
^https?:\/\/223\.5\.5\.5\/resolve url reject
^https?:\/\/cgate\.zhaopin\.com\/campusbusiness\/.*getAdvertisement url reject
^https?:\/\/cgate\.zhaopin\.com\/bdp\/tips-calc\/getSchoolHomePageTips url reject
^https?:\/\/cgate\.zhaopin\.com\/bdp\/my\/homepageMainModule url jsonjq-response-body 'del(.data.commercialModule, .data.commercialModuleV5, .data.vipModule, .data.vipModuleCardNew)'
