name: Mirror fmz200 Modules

on:
  schedule:
    - cron: '15,45 * * * *'  # 每小时的 15 分和 45 分执行
  workflow_dispatch:

jobs:
  fetch-fmz200:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    services:
      docker:
        image: xream/script-hub:latest
        ports:
          - 9100:9100
          - 9101:9101
          
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq netcat-openbsd

      - name: Wait for Docker service
        run: |
          echo "Waiting for Docker..."
          for i in {1..10}; do
            nc -z localhost 9100 && nc -z localhost 9101 && break
            sleep 5
          done

      - name: Download fmz200 Modules
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 创建目标目录（含 Beta）
          mkdir -p Modules/Loon/fmz200 Modules/Loon/fmz200/Beta
          mkdir -p Modules/Surge/fmz200 Modules/Surge/fmz200/Beta
          mkdir -p Modules/Shadowrocket/fmz200 Modules/Shadowrocket/fmz200/Beta
          mkdir -p Modules/JS/fmz200

          category="fmz200"
          encoded_category=$(echo "$category" | jq -sRr @uri)

          # ===== Loon .lpx → .plugin =====
          echo "Fetching fmz200 Loon plugins (.lpx → .plugin)"
          LOON_FILES=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/fmz200/wool_scripts/contents/Loon/plugin/split" \
            | jq -r '.[] | select(.type=="file") | .download_url')

          for URL in $LOON_FILES; do
            NAME=$(basename "$URL" .lpx)
            MAIN_OUT="Modules/Loon/fmz200/$NAME.plugin"
            BETA_OUT="Modules/Loon/fmz200/Beta/$NAME.plugin"

            echo "Downloading $URL → $MAIN_OUT"
            curl -L -H "Authorization: token $GITHUB_TOKEN" -o "$MAIN_OUT" "$URL"

            # Beta 直接复制一份
            cp "$MAIN_OUT" "$BETA_OUT"
          done

          # ===== Surge .sgmodule + Shadowrocket .srmodule =====
          echo "Fetching fmz200 Surge plugins (.sgmodule)"
          SURGE_FILES=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/fmz200/wool_scripts/contents/Surge/plugin/split" \
            | jq -r '.[] | select(.type=="file") | .download_url')

          for URL in $SURGE_FILES; do
            FILENAME=$(basename "$URL")
            NAME_NOEXT="${FILENAME%.sgmodule}"

            # 下载到 Surge 主目录
            SURGE_OUT="Modules/Surge/fmz200/$FILENAME"
            SURGE_BETA_OUT="Modules/Surge/fmz200/Beta/$FILENAME"
            echo "Downloading Surge sgmodule: $URL → $SURGE_OUT"
            curl -L -H "Authorization: token $GITHUB_TOKEN" -o "$SURGE_OUT" "$URL"
            cp "$SURGE_OUT" "$SURGE_BETA_OUT"

            # 转换成 Shadowrocket 主目录
            ENCODED_NAME=$(echo "$NAME_NOEXT" | jq -sRr @uri)
            SR_URL="http://localhost:9100/file/_start_/${URL}/_end_/${ENCODED_NAME}.sgmodule?type=loon-plugin&target=shadowrocket-module&category=${encoded_category}&nore=true"
            SR_BETA_URL="http://localhost:9101/file/_start_/${URL}/_end_/${ENCODED_NAME}.sgmodule?type=loon-plugin&target=shadowrocket-module&category=${encoded_category}&nore=true"
            SR_OUT="Modules/Shadowrocket/fmz200/${NAME_NOEXT}.srmodule"
            SR_BETA_OUT="Modules/Shadowrocket/fmz200/Beta/${NAME_NOEXT}.srmodule"

            echo "Converting → Shadowrocket: $SR_URL → $SR_OUT"
            curl -A "Surge Mac/2985" -L -o "$SR_OUT" "$SR_URL" || echo "Failed to convert $NAME_NOEXT"

            echo "Converting Beta → Shadowrocket: $SR_BETA_URL → $SR_BETA_OUT"
            curl -A "Surge Mac/2985" -L -o "$SR_BETA_OUT" "$SR_BETA_URL" || echo "Failed to convert Beta $NAME_NOEXT"
          done

      - name: Find and replace external JS resources
        continue-on-error: true
        run: |
          js_base_url="https://github.com/${GITHUB_REPOSITORY}/raw/main/Modules/JS"

          # 遍历所有主目录和 Beta 目录的 sgmodule
          for sgmodule_file in $(find Modules/Surge/fmz200 -type f -name "*.sgmodule") \
                               $(find Modules/Surge/fmz200/Beta -type f -name "*.sgmodule"); do
            author="fmz200"
            module_folder=$(basename "$sgmodule_file" .sgmodule)
            echo "Processing $sgmodule_file from folder $author for JS links"

            js_links=$(grep -v '#' "$sgmodule_file" | grep -oP 'https?://[^ ]+\.(json|js)' || echo "")
            for js_link in $js_links; do
              js_filename=$(basename "$js_link")
              local_js_path="Modules/JS/$author/$module_folder/$js_filename"
              github_js_url="$js_base_url/$author/$module_folder/$js_filename"
              mkdir -p "$(dirname "$local_js_path")"

              echo "Downloading $js_link to $local_js_path"
              if curl -A "Surge Mac/2985" -L -o "$local_js_path" "$js_link"; then
                sed -i "s|$js_link|$github_js_url|g" "$sgmodule_file"

                loon_file="Modules/Loon/$author/$module_folder.plugin"
                loon_beta_file="Modules/Loon/$author/Beta/$module_folder.plugin"
                sr_file="Modules/Shadowrocket/$author/$module_folder.srmodule"
                sr_beta_file="Modules/Shadowrocket/$author/Beta/$module_folder.srmodule"

                [ -f "$loon_file" ] && sed -i "s|$js_link|$github_js_url|g" "$loon_file"
                [ -f "$loon_beta_file" ] && sed -i "s|$js_link|$github_js_url|g" "$loon_beta_file"
                [ -f "$sr_file" ] && sed -i "s|$js_link|$github_js_url|g" "$sr_file"
                [ -f "$sr_beta_file" ] && sed -i "s|$js_link|$github_js_url|g" "$sr_beta_file"
              fi
            done
          done

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE="$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')"

          git add Modules/*

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            COMMIT_MESSAGE="Synched Modules at $DATE (UTC+8)"
            git stash
            git pull --rebase
            git stash pop || true
            git add Modules/*
            git commit -m "$COMMIT_MESSAGE"
            git push
          fi
